# Generated by Django 3.2.8 on 2021-11-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True)),
                ('employee_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.TextField(blank=True)),
                ('category', models.TextField(blank=True)),
                ('manufactured_year', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateField()),
                ('return_date', models.DateField()),
                ('part_condition', models.TextField(blank=True)),
                ('automotive_parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.part')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.employee')),
            ],
        ),
    ]
