# Generated by Django 3.2.8 on 2021-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.TextField(),
        ),
    ]
