# Generated by Django 3.2.8 on 2021-11-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211122_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_name',
            field=models.TextField(blank=True),
        ),
    ]
