# Generated by Django 3.2.8 on 2021-11-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_record_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
