# Generated by Django 3.2.8 on 2021-11-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_record_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
