# Generated by Django 3.2.8 on 2021-11-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_part_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
