# Generated by Django 3.2.8 on 2021-12-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_employee_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='part_condition',
        ),
        migrations.AddField(
            model_name='part',
            name='part_condition',
            field=models.TextField(blank=True),
        ),
    ]
