# Generated by Django 3.2.8 on 2021-12-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20211203_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_id',
            field=models.TextField(),
        ),
    ]
