# Generated by Django 3.2.8 on 2021-12-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_part_part_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
