# Generated by Django 3.2.8 on 2021-12-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_remove_employee_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
