# Generated by Django 3.2.8 on 2021-12-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('Testing', 'Testing'), ('Returned', 'Returned')], max_length=10),
        ),
    ]
