# Generated by Django 3.2.8 on 2021-11-05 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_auto_20211105_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mini_fb.person'),
            preserve_default=False,
        ),
    ]
