# Generated by Django 3.2.8 on 2021-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_statusmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='person',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_nam',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
