# Generated by Django 3.2.8 on 2021-11-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0006_rename_last_nam_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='timestamp',
            field=models.TextField(blank=True),
        ),
    ]
