# Generated by Django 3.2.8 on 2021-11-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_image_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='image_url',
        ),
    ]
